{ $define FandRunV}
{$define FandNetV}
{$define FandGraph}
{$define FandDML}
{ $define FandSQL}              { with FandNetV }
{ $define FandDemo}
{ $define FandTest}
{ $define FandAng}
{ $define Trial}                 { trial version }
{$define FandProlog}

{$N-}                       {real}
{ $N+}                       {emul}     {coproc}
{ $E+}                       {emul}
{ $E-}                                  {coproc}
{ $define Coproc}            {emul}     {coproc}